### ISSUE TITLE
Low-level h5 usage

### ISSUE THREAD

**Issue by jrt54** [bp/resqpy#26]
The UUID of various objects seems to correspond to h5 keys. I imagine there may be use-cases for resqpy just being used to get an h5-based representation of a resqml dataset if, for example, I want to use an existing tool/codebase based on h5. Are there attributes of resqml properties or functions to get the underlying h5 file and h5 key-pair for a given property.

**Comment by andy-beer** [comment]
There are a few methods in the Model class of relevance to the h5 keys:

Model.h5_uuid_and_path_for_node(node, tag = 'Values') returns a (UUID, str) pair:
- the UUID is for the external part – a special part used to identify a particular hdf5 file;
- by default resqpy will ignore this and work with a single .h5 file with the same name as the .epc;
- the str is an 'internal path name' for accessing an individual array within the hdf5 file;
- note that the node argument is not the root node, it is a node further into the xml tree, so needing knowledge of the RESQML schema definition to identify
- the tag string is typically 'Values' but also depends on the array in question (if I remember correctly)

Model.h5_uuid() returns the UUID of the 'main' hdf5 part for the model (there is usually only 1)

Model.h5_file_name(uuid = None, override = True, file_must_exist = True) returns the path of the hdf5 file:
- the uuid can be used to identify a particular external part if many hdf5 files are in use
- override causes the epc directory and filename to be used instead of that embedded in the rels xml for the external part
- file_must_exist will cause an exception to be raised if the file doesn't exist (I think)

Model.h5_access(uuid = None, mode = 'r', override = True, file_path = None) notes and returns an open file handle

Model.h5_release() closes the file

Model.h5_array_shape_and_type(h5_key_pair)  returns the shape and dtype of the array

Model.h5_array_element(h5_key_pair, index = None, cache_array = False, object = None, array_attribute = None,                dtype = 'float', required_shape = None) returns a single element from an hdf5 array and/or caches the array in memory

Model.h5_array_slice(h5_key_pair, slice_tuple)  returns a slice of an hdf5 array

Model.h5_overwrite_array_slice(h5_key_pair, slice_tuple, array_slice)  overwrites a slice of an hdf5 array
