### ISSUE TITLE
Extracting values along well bore from a property grid

### ISSUE THREAD

**Issue by gavargas22** [bp/resqpy#750]
Is there an example of how to extract the values along borehole from a property grid? What is the proper way of doing that?

I am able to extract the XYZ positions of the well bore, but it is not clear how to do the extraction in the property grid

**Comment by andy-beer** [comment]
The best way to sample grid properties along a wellbore is to go via a BlockedWell object (RESQML BlockedWellboreRepresentation). This is the intersection of a wellbore with a grid.

A new BlockedWell object can be created from an existing Grid (RESQML IjkGridRepresentation) and Trajectory (RESQML WellboreTrajectoryRepresentation) by passing the optional _grid_ and _trajectory_ arguments to the BlockedWell initialisation method. To save the BlockedWell object, you will also need to call its write_hdf5() and create_xml() methods, for which the default arguments are usually appropriate. A Model.store_epc() call is also needed at some point afterwards in order to update the epc file.

Given a blocked well, a property can be sampled from the grid onto it by calling the following BlockedWell method:

- add_grid_property_to_blocked_well(uuid_list)

The uuid list argument needs to list the UUID(s) of the grid properties that are to be sampled. To identify these uuids, you can either use the Model.uuids() or Model.uuid() catalogue functions, or work with the PropertyCollection methods having called the Grid.extract_property_collection() method. The sampled properties will already have had their hdf5 data written and xml created. The only further step to save the data is the Model.store_epc() method call (which only needs to happen once, at the end of the processing, though there is no harm in calling it more often).

The sampled properties will hold one value for each cell in the blocked well, ie. each cell that the wellbore intersects. See the Property and PropertyCollection resqpy classes for working with properties and getting at the data as numpy arrays.

The BlockedWell class includes some methods for working with measured depths, such as:

- wb_cell_for_md(md)  # identifies the blocked well cell index (and fractional distance into cell) of a given measured depth
- entry_and_exit_mds(cell_index)  # returns the measured depths at which the wellbore enters and exits the cell

I hope this helps!

**Comment by gavargas22** [comment]
This is great! Thank you so much!
