### ISSUE TITLE
Unstructured grids with Petrel

### ISSUE THREAD

**Issue by keurfonluu** [bp/resqpy#847]
Hi,

I generated a simple unstructured grid consisting of two hexahedra, but it doesn't seem to show up in Petrel. The file loads without any error and no grid seems to be found. There is a warning in the log saying that "Original CRS is undefined", but I am not sure what it means.

Does Petrel support unstructured grids? If yes, is there something missing in my files (see attached)? The grid shows up correctly in ParaView (using the Fespp plugin).

[sample_hexahedron_mesh.zip](https://github.com/user-attachments/files/17574249/sample_hexahedron_mesh.zip)

**Comment by andy-beer** [comment]
Hello,

In general I can't comment on Petrel's capabilities – you would need to contact Schlumberger about that.

I took a quick look in the data you provided and notice that your cells show as having a negative volume. That indicates that the handedness of the coordinate reference system (CRS) is not in line with your node coordinates and settings for face handedness. You might like to check the setting of the z increasing direction in the CRS, which is showing as upwards, giving a right handed CRS.

The "Original CRS is undefined" warning is probably because there is no EPSG code set in the CRS (nor other parent CRS). Most software handles this situation without trouble.

**Comment by keurfonluu** [comment]
I've fixed the handedness (and making sure that volumes are now positive) but I am still not being able to import the grid in Petrel. I guess that Petrel only supports structured grids (as the log says "Importing IJKGrids...") and is not even trying to import UnstructuredGrid. Thanks for your help and for developing/maintaining this package.
